resume/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name="accounts"
urlpatterns = [
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('send-message-with-email/',views.send_email,name='send-email'),
    path('enter-code/',views.enter_code_signup,name='e-code'),
    path('new-password/',views.new_pass,name='newpass'),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/pixel/urls.py
from django.urls import path,include
from pixel.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from pixel import sitemaps

from django.contrib.sitemaps.views import sitemap
from django.urls import path

from .sitemaps import StaticViewSitemap,BlogSitemap
from . import views

from .feeds import LatestEntriesFeed

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}
app_name = 'pixel'
urlpatterns = [
    path('',house,name='house'),
    path('resume/',resume,name='resume'),
    path('skills/',skills_,name='skills'),
    path('projects/',projects_,name='projects'),
    path('contact/',contact_,name='contact'),
    path('blog/',blog,name='blog'),
    path('single/<int:post>',single,name='single'),
    path('blog/sort-by-category<str:name><int:typ>',blog,name='blogs'),
    path('blog/sort-by-author<str:p><int:typ>',blog,name='blogsn'),
    path('sendComment/<int:post>',single,name='sendComment'),
    
    path('sitemaps.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    
    path('robots.txt', include('robots.urls')),
    path('captcha/', include('captcha.urls')),
    path("rss/feed/", LatestEntriesFeed()),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from pixel import sitemaps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pixel.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('editor/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/templates/pages/blog.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <!-- headthis -->
<section class="ftco-section" id="blog-section">
    <div class="container">
      <div class="row justify-content-center mb-5 pb-5">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <h1 class="big big-2" style="font-family: btitr;">وبلاگ</h1>
          <h2 class="mb-4" style="font-family: btitr;">وبلاگ ما</h2>
          <p style="font-family: irsans ;font-size: 19px;">اخبار و رویدادها را از طریق وبلاگ ما بررسی کنید</p>
        </div>
      </div>
      {% if name %}
      {% if typ %}
      <h4 style="text-align: right;font-family: vazir;">ترتیب بر اساس دسته‌‌بندی "{{name}}"</h3>
      {% else %}
      <h4 style="text-align: right;font-family: vazir;">ترتیب پست ها بر اساس نویسنده "{{name}}"</h3>
      {% endif %}
      {% else %}
      <h4 style="text-align: right;font-family: vazir;">تمام پست ها</h3>
      {% endif %}
      <div class="conts">
          {% for p in posts %}
          <div class="blog-entry justify-content-end" style="width: 350px;padding: 10px;background-repeat: no-repeat;
          background-color: hsl(0, 0%, 5%);border-radius: 10px;">
            <a href="{% url 'pixel:single' post=p.id %}" class="block-20">
              <img src="{{p.image.url}}" alt="img" style="background-size: contain;margin: 5px;border-radius: 10px;">
            </a>
            <div class="text mt-3 float-right d-block" style="text-align: right;">
              <div class="d-flex align-items-center mb-3 meta">
                <p class="mb-0">
                  <span class="mr-2" style="font-family: vazir ;">{{p.p_date|naturalday}}</span>
                  <a href="{% url 'pixel:single' post=p.id %}" class="mr-2" style="font-family: vazir ;">{{p.uname.fname}} {{p.uname.lname}}</a>
                  <a href="{% url 'pixel:single' post=p.id %}" class="meta-chat"><span class="icon-chat"></span> بازدید کننده: {{p.cview|intword}}</a>
                </p>
              </div>
              <h3 class="heading" style="font-family: btitr ;"><a href="{% url 'pixel:single' post=p.id %}">{{p.title}}</a></h3>
              <p style="font-family: irsans ;">
                {{p.desc|truncatewords:30}}
              </p>
            </div>
          </div>
          {% endfor %}
      </div>
    </div>
  </section>
  <section class="ftco-section ftco-hireme img margin-top" style="background-image: url(../images/bg_1.jpg)">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-7 ftco-animate text-center">
          <h2 style="font-family: irsans;">من برای <span> فریلنسری </span> نیز در دسترس هستم</h2>
          <p class="mb-0"><a href="#" class="btn btn-primary py-3 px-5">استخدام من</a></p>
        </div>
      </div>
    </div>
  </section>

<!-- footthis -->
{% endblock %}

resume/templates/pages/categoris.html
<ul class="categories">
    <li><a href="#">دسته بندی اول <span>(12)</span></a></li>
</ul>

resume/templates/pages/contact.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
    <!-- headthis -->
<section class="ftco-section contact-section ftco-no-pb" id="contact-section">
    <div class="container">
      <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <h1 class="big big-2">ارتباط</h1>
          <h2 class="mb-4" style="font-family: btitr;">ارتباط با من</h2>
          <p style="font-family: irsans ;font-size: 19px;">{{contactD}}</p>
        </div>
      </div>
      <div class="row d-flex contact-info mb-5">
        <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          <div class="align-self-stretch box p-4 text-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="icon-map-signs"></span>
            </div>
            <h3 class="mb-4" style="font-family: irsans;"> آدرس محل کار</h3>
            <p style="font-family: irsans;">{{user.location}}</div>
        </div>
        <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          <div class="align-self-stretch box p-4 text-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="icon-phone2"></span>
            </div>
            <h3 class="mb-4" style="font-family: irsans;">شماره تماس</h3>
            <p><a href="tel://09010926908" style="font-family: vazir;">{{user.tellNumber}}</a></p>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          <div class="align-self-stretch box p-4 text-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="icon-paper-plane"></span>
            </div>
            <h3 class="mb-4" style="font-family: irsans;">ایمیل</h3>
            <p><a href="#"><span class="__cf_email__"
                  data-cfemail="f29b9c949db28b9d8780819b8697dc919d9f">{{user.email}}</span></a></p>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          <div class="align-self-stretch box p-4 text-center">
            <div class="icon d-flex align-items-center justify-content-center">
              <span class="icon-globe"></span>
            </div>
            <h3 class="mb-4" style="font-family: irsans;">وبسایت</h3>
            <p><a href="#">website</a></p>
          </div>
        </div>
      </div>
      <div class="row no-gutters block-9" style="padding: 40px;">
        <div class="col-md-6 order-md-last d-flex" style="width:500px;height:600px">
          <form action="{% url 'pixel:contact' %}" class="bg-light p-4 p-md-5 contact-form" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="form-group" style="text-align: center;">
              <input type="submit" value="ارسال" class="btn btn-primary py-3 px-5">
            </div>
          </form>
        </div>
        <div class="col-md-6 d-flex">
          <div class="img"><img src="{% static 'images/about.jpg' %}" alt="about" srcset="" style="width: 500px;height: 600px;"></div>
        </div>
      </div>
    </div>
</section>
<!-- footthis -->
{% endblock %}

resume/templates/pages/email_window.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        h1{
            text-align: center;
            align-content: center;
            background-color: #6374f5;
        }
        p{
            font-size: 40px;
            direction: rtl;
            text-align: right;
        }
    </style>
</head>
<body>
    <h1>
        !خوش آمدید
    </h1>
    {% if blank %}
    <p>
        ♥{{fname}}♥ گرامی به سایت ما خوش‌آمدید <br>
        گذرواژه شما: '{{absnumb}}'
    </p>
    {% else %}
    <p>
    ♥{{fname}}♥ جون به سایت ما خوش‌آمدید <br>
    گذرواژه شما: '{{absnumb}}'
    </p>
    {% endif %}
    <br>
    <br>
</body>
</html>

resume/templates/pages/enterCode.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Login V8</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="{% static 'enter_the_code/images/icons/favicon.ico'  %}" />

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/bootstrap/css/bootstrap.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/animate/animate.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/css-hamburgers/hamburgers.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/animsition/css/animsition.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/select2/select2.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/vendor/daterangepicker/daterangepicker.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'enter_the_code/css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/Dstyle.css' %}">

<meta name="robots" content="noindex, follow">
</head>
<body>
	{% for message in messages %}
    <p class="{{message.tags}}" id="{{message.tags}}" style="position: absolute;">{{message}}</p>
    <script>
      setTimeout(()=>{document.getElementById("msg-success").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-error").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-warning").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-info").style.display = "none"},4000)
    
    </script>
    {% endfor %}
<div class="limiter">
<div class="container-login100">
<div class="wrap-login100">
<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="post" action="{% url 'accounts:e-code' %}">
	{% csrf_token %}
<span class="login100-form-title" style="font-family: vazir;">
تایید صلاحیت
</span>
<div class="wrap-input100 validate-input m-b-16" data-validate="لطفا گذرواژه موقتی را وارد کنید">
<input class="input100" type="text" name="code" placeholder="گذرواژه موقتی" style="font-family: vazir;" required>
<span class="focus-input100"></span>
</div>
<div class="wrap-input100 validate-input" data-validate="Please enter password">
<span class="focus-input100"></span>
</div>
<div class="text-right p-t-13 p-b-23">
<span class="txt1">
</span>
<a href="{% url 'accounts:send-email' %}" class="txt2" style="font-family: irsans;">
ارسال مجدد 🔄
</a>
</div>
<div class="container-login100-form-btn">
<input type="submit" value="تایید" class="login100-form-btn" style="font-family: vazir;">
</div>
<div class="flex-col-c p-t-170 mb">
</div>
</form>
</div>
</div>
</div>

<script src="{% static 'enter_the_code/vendor/jquery/jquery-3.2.1.min.js' %}"></script>

<script src="{% static 'enter_the_code/vendor/animsition/js/animsition.min.js' %}"></script>

<script src="{% static 'enter_the_code/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'enter_the_code/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'enter_the_code/vendor/select2/select2.min.js' %}"></script>

<script src="{% static 'enter_the_code/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'enter_the_code/vendor/daterangepicker/daterangepicker.js' %}"></script>

<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>
</body>
</html>

resume/templates/pages/inc.html
{% load static %}
{% load humanize %}
{% for r in posts %}
<div class="block-21 mb-4 d-flex"style="text-align: right;">
<a class="blog-img mr-4" href="{% url 'pixel:single' post=r.id %}"><img src="{{r.image.url}}" alt="img" style="width: inherit;height: inherit;display: inline-block;position: relative;left:9px;"></a>
<div class="text">
<h3 class="heading"><a href="{% url 'pixel:single' post=r.id %}" style="font-family: btitr;">{{r.title}}</a></h3>
<div class="meta">
<div><a href="{% url 'pixel:single' post=r.id %}" style="font-family: irsans;"><span class="icon-calendar"></span>{{r.p_date|naturaltime}}</a></div>
<div><a href="{% url 'pixel:single' post=r.id %}" style="font-family: irsans"><span class="icon-person"></span>{{r.uname.fname}} {{r.uname.lname}}</a></div>
<div><a href="{% url 'pixel:single' post=r.id %}" style="font-family: irsans;"><span class="icon-chat"></span>بازدید کننده:{{r.cview|naturaltime}}</a></div>
{% for i in r.category.all %}
<a href="{% url 'pixel:single' post=r.id %}"><span style="border-width: 2px;border-style: ridge;display: inline-block;margin-top: 2px;padding: 4px;font-size: 12px;font-family: vazir;border-radius: 10px;">{{i.name}} </span></a>
{% endfor %}
</div>
</div>
</div>
{% endfor %}

resume/templates/pages/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Login V1</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %} " />

  <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/Dstyle.css' %}">

  <meta name="robots" content="noindex, follow">
</head>

<body>
  {% for message in messages %}
    <p class="{{message.tags}}" id="{{message.tags}}" style="position: absolute;">{{message}}</p>
    <script>
      setTimeout(()=>{document.getElementById("msg-success").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-error").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-warning").style.display = "none"},4000)
      setTimeout(()=>{document.getElementById("msg-info").style.display = "none"},4000)
    
    </script>
    {% endfor %}
  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">
        <div class="login100-pic js-tilt" data-tilt>
          <img src="{% static 'login/images/img-01.png' %}" alt="IMG">
        </div>
        <form class="login100-form validate-form" action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
          <span class="login100-form-title" style="font-family: vazir;">
            ورود به حساب کاربری
          </span>
          <div style="text-align:right;padding: 0 20px;margin-bottom: 10px;">
          <p style="font-family: vazir;font-size: 20px;">ورود با</p>
          <span style="font-family: vazir;font-size: 16px;" >نام کاربری <input type="radio" name="enter-mode" onclick="check()" value="1" checked id="ur"></span>
          <span style="float:left;font-family: vazir;font-size: 16px;" >ایمیل <input type="radio" onclick="check()" name="enter-mode" value="2" id="er"></span>
          </div>
          <div class="wrap-input100" style="font-family: m;" id="uname">
            <input class="input100" type="text" name="username" id="euname"style="font-family: Verdana, Geneva, Tahoma, sans-serif;" placeholder="نام کاربری">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </span>
          </div>
          <div class="wrap-input100" style="font-family: m;display: none;" id="email">
            <input class="input100" type="email" name="email" id="eimail" style="font-family: Verdana, Geneva, Tahoma, sans-serif;" placeholder="ایمیل">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </span>
          </div>
          <div class="wrap-input100 validate-input" style="font-family: m;" data-validate="پسورد را وارد کنید">
            <input class="input100" type="password" style="font-family: m;" name="password" placeholder="گذرواژه">
            <span class="focus-input100"></span>
            <span class="symbol-input100">
              <i class="fa fa-lock" aria-hidden="true"></i>
            </span>
          </div>
          <div class="container-login100-form-btn">
            <button class="login100-form-btn" style="font-family: irsans;">
              ورود
            </button>
          </div>
          <div class="text-center p-t-12">
            <span class="txt1" style="font-family: irsans;">
              در صورت فراموشی نام کاربری / گذرواژه
            </span>
            <a class="txt2" href="{% url 'accounts:newpass' %}" style="font-family: irsans;">
              کلیک کنید
            </a>
          </div>
          <div class="text-center p-t-136">
            <a class="txt2" href="{% url 'accounts:signup' %}" style="font-family: btitr;">
              یکی بساز
              <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>

  <script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
  <script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>

  <script src="{% static 'login/vendor/tilt/tilt.jquery.min.js' %}"></script>
  <script>
    $('.js-tilt').tilt({
      scale: 1.1
    })
  </script>

  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
  <script>
    let user_radio=document.getElementById("ur")
    let email_radio=document.getElementById("er")
    function check(){
    if(user_radio.checked) {
      document.getElementById("uname").style.display="block"
      document.getElementById("euname").required = true
      document.getElementById("eimail").required = false
      document.getElementById("email").style.display="none"
    }
    else if(email_radio.checked) {
      document.getElementById("uname").style.display="none"
      document.getElementById("eimail").required = true
      document.getElementById("euname").required = false
      document.getElementById("email").style.display="block"
    }}
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
  </script>

  <script src="{% static 'login/js/main.js' %}"></script>
</body>

</html>

resume/templates/pages/projects.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<!-- headthis -->
<section class="ftco-section ftco-project" id="projects-section">
    <div class="container">
      <div class="row justify-content-center pb-5">
        <div class="col-md-12 heading-section text-center ftco-animate">
          <h1 class="big big-2">پروژه‌ها</h1>
          <h2 class="mb-4" style="font-family: btitr;">پروژه‌ها</h2>
          <p style="font-family: irsans ;font-size: 19px;"> 
          {{projectD}}  
          
          <ul style="text-align: right;">
          <span style="font-family: vazir;font-weight: bold;">پرژه‌های من شامل:</span>
          {% for p in projects %}
            <li style="margin-right: 30px;font-family: vazir;"><span style="color:darkseagreen">{{p.proNam}}: </span>{{p.dis}}
            </li>
          {% endfor %}
          </ul>
        </p>
        </div>
      </div>
      <div class="row">
        {% for p in projects %}
        <div class="col-md-4">
          <div class="project img ftco-animate d-flex justify-content-center align-items-center" id="pic1">
            <div class="overlay"></div>
            <div class="text text-center p-4">
              <h3><a href="#">{{p.proNam}}</a></h3>
              <span></span>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
<!-- footthis -->
{% endblock %}

resume/templates/pages/single.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
{% load tmps %}
{% load humanize %}
<section class="hero-wrap js-fullheight"  data-stellar-background-ratio="0.5" id="Bismooti">
<div class="overlay"></div>
<div class="container">
<div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
<div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
<h1 class="mb-3 bread">از رویداد های ما باخبر شوید</h1>
</div>
</div>
</div>
</section>
<section class="ftco-section">
<div class="container">
<div class="row">
<div class="col-lg-8 ftco-animate">
<img src="{{post.image.url}}" alt class="img-fluid">
</p>
<h2 class="mb-3" style="direction: rtl;text-align: right;font-family: btitr;">{{post.title}}</h2><h4 style="text-align: right;font-family: m;">بازدید کننده: {{post.cview|intword}}</h6>

<p style="text-align: right;font-family: irsans;">{{post.desc|safe}}</p>
<div class="tag-widget post-tag-container mb-5 mt-5">
<div class="tagcloud">
</div>
</div>
<div class="about-author d-flex p-4 bg-dark">
<div class="bio mr-5" style="text-align: right;direction: rtl;">
<img src="{{post.uname.image.url}}" alt="Image placeholder" class="img-fluid mb-4">
</div>
<div class="desc"style="text-align: right;direction: rtl;">
<a href="{% url 'pixel:blogsn' p=post.uname.username typ=0 %}"><h3 style="font-family: vazir;">{{post.uname.fname}} {{post.uname.lname}}</h3></a>
<p style="font-family: irsans">{{post.uname.about}}</p>
</div>
</div>
<div class="pt-5 mt-5">
<h3 class="mb-5" style="text-align: right;font-family: m;">{{lengthc|intword}} نظر</h3>
<ul class="comment-list">
{% for c in comments %}
<li class="comment">
<div class="vcard bio" style="text-align: right;direction: rtl;">
{% if c.uname %}<img src="{{c.uname.image.url}}" alt="Image placeholder" style="text-align: right;direction: rtl;">{% endif %}
</div>
<div class="comment-body"style="text-align: right;direction: rtl;">
{% if c.uname %}<h3>{{c.uname.username}}</h3>{% else %}<h3>ناشناس</h3>{% endif %}
<div class="meta">{{c.c_date|naturaltime}}
<p>{{c.subject}}</p>
<p><a href="#" class="reply">پاسخ</a></p>
</div>
</li>
{% endfor %}
<li class="comment">

<div class="comment-form-wrap pt-5">
<h3 class="mb-5" style="text-align: right;font-family: vazir;">نظر بدهید</h3>
<form action="{% url 'pixel:sendComment' post=post.id%}" method="post" class="p-5 bg-dark" style="text-align: right;direction: ltr;">{% csrf_token %}
{{comform.as_p}}
<input type="submit" value="send">
</form>
</div>
</div>
</div> 
<div class="col-lg-4 sidebar ftco-animate">
<div class="sidebar-box">
<form action="#" class="search-form">
<div class="form-group">
<span class="icon icon-search"></span>
<input type="text" class="form-control" placeholder="Type a keyword and hit enter">
</div>
</form>
</div>
<div class="sidebar-box ftco-animate" style="text-align: right;">
<h3 class="heading-sidebar" style="font-size: 20px;font-family: btitr;">دسته‌بندی ها</h3>
<ul class="categories">
{% for cs in post.category.all %}
<li><a href="{% url 'pixel:blogs' name=cs.name typ=1 %}" style="font-size: 19px;font-family: vazir;">{{cs.name}}<span>(دیدن)</span></a></li>
{% endfor %}
</ul>
</div>
<div class="sidebar-box ftco-animate"style="text-align: right;">
<h3 class="heading-sidebar">پست های اخیر</h3>

{% latest_post %}

</div>
<div class="sidebar-box ftco-animate">
<h3 class="heading-sidebar">Paragraph</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
</div>
</div>
</div>
</div>
</section> 
{% endblock %}