resume/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name="accounts"
urlpatterns = [
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('send-message-with-email/',views.send_email,name='send-email'),
    path('enter-code/',views.enter_code_signup,name='e-code'),
    path('new-password/',views.new_pass,name='newpass'),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/pixel/urls.py
from django.urls import path,include
from pixel.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from pixel import sitemaps

from django.contrib.sitemaps.views import sitemap
from django.urls import path

from .sitemaps import StaticViewSitemap,BlogSitemap
from . import views

from .feeds import LatestEntriesFeed

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}
app_name = 'pixel'
urlpatterns = [
    path('',house,name='house'),
    path('resume/',resume,name='resume'),
    path('skills/',skills_,name='skills'),
    path('projects/',projects_,name='projects'),
    path('contact/',contact_,name='contact'),
    path('blog/',blog,name='blog'),
    path('single/<int:post>',single,name='single'),
    path('blog/sort-by-category<str:name><int:typ>',blog,name='blogs'),
    path('blog/sort-by-author<str:p><int:typ>',blog,name='blogsn'),
    path('sendComment/<int:post>',single,name='sendComment'),
    
    path('sitemaps.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    
    path('robots.txt', include('robots.urls')),
    path('captcha/', include('captcha.urls')),
    path("rss/feed/", LatestEntriesFeed()),
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/resume/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from pixel import sitemaps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pixel.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('editor/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

resume/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa">

<head>
  <title>mohsen khayyat - web developer and data scientist</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/Dstyle.css' %}">
  <meta name="keywords" content="محسن خیاط,رزومه,طراحی سایت">
  <meta name="description"
    content="من محسن خیاط هستم متخصص و طراح سایت با سه سال تجربه‌ کاری در حوزه های مختلف از جمله برنامه‌نویسی ویندوز">
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
    <div class="container">

      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
        data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav nav ml-auto">
          <li class="nav-item"><a href="{% url 'pixel:house' %}" class="nav-link"
              style="font-size: 20px;font-weight: bold;"><span>صفحه
                اصلی</span></a></li>
          <li class="nav-item"><a href="{% url 'pixel:resume' %}" class="nav-link"
              style="font-size: 18px;"><span>رزومه</span></a></li>
          <li class="nav-item"><a href="{% url 'pixel:skills' %}" class="nav-link"
              style="font-size: 18px;"><span>مهارت‌ها</span></a></li>
          <li class="nav-item"><a href="{% url 'pixel:projects' %}" class="nav-link"
              style="font-size: 18px;"><span>پروژه‌ها</span></a></li>

          <li class="nav-item"><a href="{% url 'pixel:contact' %}" class="nav-link"
              style="font-size: 18px;"><span>ارتباط</span></a></li>

          <li class="nav-item"><a href="{% url 'pixel:blog' %}" class="nav-link"
              style="font-size: 18px;"><span>وبلاگ</span></a></li>
          {% if is_user %}
          <p style="padding-top: 15px;text-align: left;color: rgb(130, 130, 130);font-family: vazir;margin-right: 140px;font-size: 12px;">
          شما هم اکنون دارای حساب کاربری هستید <a href="{% url 'accounts:logout' %}" style="color: rgb(255, 255, 255);display: inline-block;width: 5rem;height: 2rem; background-color: red;border-radius: 10px;border-width: 2px;border-color: rgba(240, 248, 255, 0);outline-width: 2px;outline-style: solid;outline-color: red;text-align: center;align-content: center;margin-right: 5px;">خروج از حساب</a>
          </p>
          {% else %}
          <li class="nav-item" style="margin-right: 140px;"><a href="{% url 'accounts:signup' %}" class="nav-link"
              style="font-size: 15px;"><span>➡ایجاد حساب</span></a></li>
          <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link"
              style="font-size: 15px;"><span>➡ورود به حساب</span></a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% for message in messages %}
  <p class="{{message.tags}}" id="{{message.tags}}" style="position: sticky;">{{message}}</p>
  <script>
    setTimeout(() => { document.getElementById("msg-success").style.display = "none" }, 4000)
    setTimeout(() => { document.getElementById("msg-error").style.display = "none" }, 4000)
    setTimeout(() => { document.getElementById("msg-warning").style.display = "none" }, 4000)
    setTimeout(() => { document.getElementById("msg-info").style.display = "none" }, 4000)

  </script>
  {% endfor %}
  {% block content %}
  <!-- content -->
  {% endblock %}
  <footer class="ftco-footer ftco-section" id="con-st" style="text-align: right;direction: rtl;">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2" style="font-family: vazir;">درمورد</h2>
            <p style="font-family: irsans;">{{downnav}}
            </p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-4">
            <h2 class="ftco-heading-2" style="margin-right: 50px;font-family: vazir;">پیوند‌ها</h2>
            <ul class="list-unstyled">
              <li style="font-family: irsans;"><a href="{% url 'pixel:house' %}"><span
                    class="icon-long-arrow-right mr-2"></span> {{link_1}}</a></li>
              <li style="font-family: irsans;"><a href="{% url 'pixel:resume' %}"><span
                    class="icon-long-arrow-right mr-2"></span> {{link_2}}</a></li>
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{link_3}}</a></li>
              <li style="font-family: irsans;"><a href="{% url 'pixel:projects' %}"><span
                    class="icon-long-arrow-right mr-2"></span> {{link_4}}</a></li>
              <li style="font-family: irsans;"><a href="{% url 'pixel:contact' %}"><span
                    class="icon-long-arrow-right mr-2"></span> {{link_5}}</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2" style="margin-right: 50px;font-family: vazir;">سرویس‌ها</h2>
            <ul class="list-unstyled">
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{service_1}}</a></li>
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{service_2}}</a></li>
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{service_3}}</a></li>
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{service_4}}</a></li>
              <li style="font-family: irsans;"><a href="#"><span class="icon-long-arrow-right mr-2"></span>
                  {{service_5}}</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2" style="font-family: vazir;">سوال داری؟</h2>
            <div class="block-23 mb-3">
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text"
                    style="font-family: irsans;">{{address}}</span></li>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text"
                      style="font-family: vazir;">{{cNumber}}</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span class="__cf_email__"
                        data-cfemail="f1989f979eb1889e8483959e9c90989fdf929e9c">{{email}}</span></span></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" />
    </svg></div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/Fadmin.js' %}"></script>
  <script src="{% static 'js/prim.js' %}"></script>
  {% if not is_user %}
  <script></script>
  {% else %}
  <script></script>
  {% endif %}

  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
  </script>
  <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317"
    integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA=="
    data-cf-beacon='{"rayId":"85d39db2fbbf9b37","b":1,"version":"2024.2.1","token":"cd0b4b3a733644fc843ef0b185f98241"}'
    crossorigin="anonymous"></script>
</body>

</html>

resume/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <section id="home-section" class="hero">
    <div class="home-slider  owl-carousel">
      <div class="slider-item ">
        <div class="overlay"></div>
        <div class="container">
          <div class="row d-md-flex no-gutters slider-text align-items-end justify-content-end"
            data-scrollax-parent="true">
            <div class="one-third js-fullheight order-md-last img" style="background-image:url(static/images/bg_1.png);">
              <div class="overlay"></div>
            </div>
            <div class="one-forth d-flex  align-items-center ftco-animate"
              data-scrollax=" properties: { translateY: '70%' }">
              <div class="text" style="text-align: right;">
                <span class="subheading" style="font-size: 26px;">سلام!</span>
                <h1 class="mb-4 mt-3">من <span>{{user.fname}}</span> هستم</h1>
                <h2 class="mb-4">با سه سال تجربه کاری :)</h2>
                <p><b><a href="#" class="btn btn-primary py-3 px-4"><b>استخدام من</b></a> <a href="#"
                      class="btn btn-white btn-outline-white py-3 px-4">آثار من</a></b></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="slider-item">
        <div class="overlay"></div>
        <div class="container">
          <div class="row d-flex no-gutters slider-text align-items-end justify-content-end"
            data-scrollax-parent="true">
            <div class="one-third js-fullheight order-md-last img" style="background-image:url(static/images/bg_2.png);">
              <div class="overlay"></div>
            </div>
            <div class="one-forth d-flex align-items-center ftco-animate"
              data-scrollax=" properties: { translateY: '70%' }">
              <div class="text" style="text-align: right;">
                <span class="subheading" style="font-size: 26px;">سلام!</span>
                <h1 class="mb-4 mt-3">شعار من <span>دقت، خلاقیت و کار تیمی</span> است </h1>
                <p><a href="#" class="btn btn-primary py-3 px-4">استخدام من</a> <a href="#"
                    class="btn btn-white btn-outline-white py-3 px-4">آثار من</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="ftco-about img ftco-section ftco-no-pb" id="about-section">
    <div class="container">
      <div class="row d-flex">
        <div class="col-md-6 col-lg-5 d-flex">
          <div class="img-about img d-flex align-items-stretch">
            <div class="overlay"></div>
            <div class="img d-flex align-self-stretch align-items-center"
              style="background-image:url(static/images/bg_1.png);">
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-7 pl-lg-5 pb-5" style="direction: rtl;text-align: right;">
          <div class="row justify-content-start pb-3">
            <div class="col-md-12 heading-section ftco-animate">
              <h1 class="big">درباره من</h1>
              <h2 class="mb-4" style="font-family: btitr;">{{user.fname}}</h2>
              <p style="font-family: irsans ;font-size: 19px;">
                {{user.about}}
              </p>
              <ul class="about-info mt-4 px-md-0 px-2">
                <li class="d-flex"><span style="font-size: 20px;">نام:</span> <span style="font-family: vazir;">{{user.fname}} {{user.lname}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">تاریخ تولد:</span> <span style="font-family: vazir;">{{user.birthday}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">محل زندگی:</span> <span
                    style="font-family: vazir;">{{user.location}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">کد پستی:</span> <span
                    style="font-family: vazir;">{{user.cod_posti}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">ایمیل:</span> <span><a
                      href="#" class="__cf_email__"
                      data-cfemail="187b74796a736c70777568587f75797174367b7775">{{user.email}}</a></span>
                </li>
                <li class="d-flex"><span style="font-size: 20px;">شماره تماس: </span> <span
                    style="font-family: vazir;">{{user.tellNumber}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">تحصیلات: </span> <span
                    style="font-family: vazir;">{{user.education}}</span></li>
                <li class="d-flex"><span style="font-size: 20px;">زبان‌ها: </span> <span
                    style="font-family: vazir;">{{user.langs}}</span></li>
              </ul>
            </div>
          </div>
          <div class="counter-wrap ftco-animate d-flex mt-md-3">
            <div class="text">
              <p class="mb-4">
                <span class="number" data-number="{{user.t_p}}" style="font-family: vazir;">{{user.t_p}}</span>
                <span>پروژه خاتمه یافته</span>
              </p>
              <p><a href="#" class="btn btn-primary py-3 px-3">Download CV</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

resume/templates/testUD.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Sin = {{answer}}</p>
    <p>Cos = {{answer2}}</p>
    <p>Tan = {{answer3}}</p>
    <p>acc = {{obj}}</p>
</body>
</html>

resume/templates/testdb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        p{
            font-size: 20px;
        }
    </style>
</head>
<body>
    <h1>TEST For DataBase</h1>
    {% for i in accounts %}
    {% if i.power >= 400 %}
    <h2>{{i.typeofacc}}</h2>
    <p>{{i.id}}.{{i.codeacc}} - {{i.power}}</p>
    {% endif %}
    {% endfor %}
</body>
</html>